services:
  - type: web
    name: tickets-ai
    env: python
    pythonVersion: 3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ticket_ai.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ticket_ai.settings
